@startuml
'https://plantuml.com/sequence-diagram

left to right direction
skin rose

entity cliente{
*rut
*nombre
}

entity vendedor {
*rut
*nombre
*anios de experiencia
}

entity mantenimiento{
*id
*fecha
*tipo de mantenimiento
*descripcion
}

entity vehiculo{
*id
*marca
*anio de fabricacion
*kilometraje
*tipo de vehiculo
}

entity boleta{
*id
*fecha de emision
*precio total
}



@enduml